对 files sources scripts 目录中部分软件包进行更新
1、更新部分软件版本、构建脚本、补丁等资源文件。
2、增加部分软件包以满足依赖需求。
3、调整部分软件包所在组。

diff --git a/loongarch64/scripts/step/cross-tools/binutils b/loongarch64/scripts/step/cross-tools/binutils
--- a/loongarch64/scripts/step/cross-tools/binutils
+++ b/loongarch64/scripts/step/cross-tools/binutils
@@ -4,16 +4,16 @@ source env/function.sh
 source env/cross-tools/custom
 export STEP_BUILDNAME=cross-tools
 export STEP_PACKAGENAME=binutils
-export PACKAGE_VERSION=2.45.1
-export RESOURCEDIR=${NEW_TARGET_SYSDIR}/files/cross-tools/binutils/2.45.1/
-rm -rf ${BUILD_DIRECTORY}/binutils-2.45.1
-tar xvf ${DOWNLOADDIR}/binutils-2.45.1.tar.xz -C ${BUILD_DIRECTORY} 
-pushd ${BUILD_DIRECTORY}/binutils-2.45.1
+export PACKAGE_VERSION=2.46.0
+export RESOURCEDIR=${NEW_TARGET_SYSDIR}/files/cross-tools/binutils/2.46.0/
+rm -rf ${BUILD_DIRECTORY}/binutils-2.46.0
+tar xvf ${DOWNLOADDIR}/binutils-2.46.0.tar.xz -C ${BUILD_DIRECTORY} 
+pushd ${BUILD_DIRECTORY}/binutils-2.46.0
 	
 	rm -rf gdb* libdecnumber readline sim
 	mkdir -p tools-build
 	pushd tools-build
-    	CC=gcc AR=ar AS=as CFLAGS=$([[ $(gcc -dumpversion) -ge 13 ]] && echo "${CFLAGS} -Wno-error=dangling-pointer" || echo "${CFLAGS}") \
+    	CC=gcc AR=ar AS=as CFLAGS=$([[ $(gcc -dumpversion) -ge 13 ]] && echo "${CFLAGS} -Wno-error=dangling-pointer" || echo "${CFLAGS} -Wno-error=format-truncation") \
 	    ../configure --prefix=${CROSSTOOLS_DIR} --build=${CROSS_HOST} --host=${CROSS_HOST} \
 	                 --target=${CROSS_TARGET} --with-sysroot=${SYSROOT_DIR} --disable-nls \
 	                 --disable-static --enable-64-bit-bfd
@@ -23,4 +23,4 @@ pushd ${BUILD_DIRECTORY}/binutils-2.45.1
     	cp -v ../include/libiberty.h ${SYSDIR}/sysroot/usr/include
     popd
 popd 
-rm -rf ${BUILD_DIRECTORY}/binutils-2.45.1
+rm -rf ${BUILD_DIRECTORY}/binutils-2.46.0
